/*
 * generated by Xtext 2.17.0
 */
package edu.kit.ipd.sdq.modsim.simspec.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpecificationLanguageRuntimeModule extends AbstractSpecificationLanguageRuntimeModule {
}
