/*
 * generated by Xtext 2.17.0
 */
package edu.kit.ipd.sdq.modsim.simspec.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpecificationLanguageStandaloneSetup extends SpecificationLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new SpecificationLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
