/*
 * generated by Xtext 2.17.0
 */
package edu.kit.ipd.sdq.modsim.simspec.language.ide


/**
 * Use this class to register ide components.
 */
class SpecificationLanguageIdeModule extends AbstractSpecificationLanguageIdeModule {
}
